# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companynames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('marketcap', models.FloatField(default=0)),
                ('sector', models.CharField(max_length=100)),
                ('industry', models.TextField(default='*')),
            ],
        ),
    ]
