# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynames',
            name='industry',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companynames',
            name='marketcap',
            field=models.CharField(max_length=200),
        ),
    ]
