# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170520_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='compinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=25)),
                ('tradetime', models.CharField(max_length=200)),
                ('tradeprice', models.CharField(max_length=200)),
            ],
        ),
    ]
